const express = require('express')
const app = express()
const dotenv = require('dotenv')
const mongoose = require('mongoose')
const authRoute=require('./routes/auth')
const userRoute=require('./routes/user')
const jobRoute=require("./routes/job")
const bookMarkRoute=require("./routes/bookmark")
const chatRoute=require("./routes/chat")
const messageRoute=require("./routes/messages")
dotenv.config()
//process.env.VARIABLE_NAME

mongoose.connect(process.env.MONGO_URL,)
  .then(() => console.log('MongoDB connected'))
  .catch(err => console.error('MongoDB connection error:', err));
  app.use(express.json())
app.use("/api/",authRoute)
app.use("/api/users",userRoute)
app.use("/api/jobs", jobRoute)
app.use("/api/bookmarks", bookMarkRoute)
app.use("/api/chats", chatRoute)
app.use("/api/messages", messageRoute)
app.listen(process.env.PORT|| 5002,()=>{console.log(`Example app listening on port ${process.env.PORT||5002}!`)})